name: build push nuget to registry

on:
  workflow_call:
    inputs:
      package-id:
        type: string
        description: The name of the package
        required: true
      registry:
        type: string
        description: The registry to push the package to
        required: false
        default: https://api.nuget.org/v3/index.json
    secrets:
      nuget_api_key:
        description: The API key to use for pushing the package
        required: true

env:
  VERSION:

jobs:
  Build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Get version from Directory.build.props
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=<VersionPrefix>).*(?=</VersionPrefix>)' Directory.Build.props)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version found: $VERSION"

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Package the project
        run: |
          dotnet pack "src/${{ inputs.package-id }}/${{ inputs.package-id }}.csproj" -p:Version=${{ env.VERSION }} --configuration Release

      - name: Publish the package
        run: |
          dotnet nuget push "src/${{ inputs.package-id }}/bin/Release/${{ inputs.package-id }}.${{ env.VERSION }}.nupkg" --api-key ${{ secrets.nuget_api_key }} --source "${{ inputs.registry }}"

